package com.springboot.demo.model;

public class EmployeeEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.f_id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.f_name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.f_address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.f_age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.f_phoneNo
     *
     * @mbg.generated
     */
    private Integer phoneno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.f_id
     *
     * @return the value of t_employee.f_id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.f_id
     *
     * @param id the value for t_employee.f_id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.f_name
     *
     * @return the value of t_employee.f_name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.f_name
     *
     * @param name the value for t_employee.f_name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.f_address
     *
     * @return the value of t_employee.f_address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.f_address
     *
     * @param address the value for t_employee.f_address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.f_age
     *
     * @return the value of t_employee.f_age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.f_age
     *
     * @param age the value for t_employee.f_age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.f_phoneNo
     *
     * @return the value of t_employee.f_phoneNo
     *
     * @mbg.generated
     */
    public Integer getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.f_phoneNo
     *
     * @param phoneno the value for t_employee.f_phoneNo
     *
     * @mbg.generated
     */
    public void setPhoneno(Integer phoneno) {
        this.phoneno = phoneno;
    }
}