package com.springboot.demo.model;

import java.util.Date;

public class PermissionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.f_version
     *
     * @mbg.generated
     */
    private Byte version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.f_category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.f_sub_category
     *
     * @mbg.generated
     */
    private String subCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.f_permission_name
     *
     * @mbg.generated
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.f_description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.f_permission_value
     *
     * @mbg.generated
     */
    private String permissionValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.f_status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.f_id
     *
     * @return the value of t_permission.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.f_id
     *
     * @param id the value for t_permission.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.f_version
     *
     * @return the value of t_permission.f_version
     *
     * @mbg.generated
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.f_version
     *
     * @param version the value for t_permission.f_version
     *
     * @mbg.generated
     */
    public void setVersion(Byte version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.f_category
     *
     * @return the value of t_permission.f_category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.f_category
     *
     * @param category the value for t_permission.f_category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.f_sub_category
     *
     * @return the value of t_permission.f_sub_category
     *
     * @mbg.generated
     */
    public String getSubCategory() {
        return subCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.f_sub_category
     *
     * @param subCategory the value for t_permission.f_sub_category
     *
     * @mbg.generated
     */
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory == null ? null : subCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.f_permission_name
     *
     * @return the value of t_permission.f_permission_name
     *
     * @mbg.generated
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.f_permission_name
     *
     * @param permissionName the value for t_permission.f_permission_name
     *
     * @mbg.generated
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.f_description
     *
     * @return the value of t_permission.f_description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.f_description
     *
     * @param description the value for t_permission.f_description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.f_permission_value
     *
     * @return the value of t_permission.f_permission_value
     *
     * @mbg.generated
     */
    public String getPermissionValue() {
        return permissionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.f_permission_value
     *
     * @param permissionValue the value for t_permission.f_permission_value
     *
     * @mbg.generated
     */
    public void setPermissionValue(String permissionValue) {
        this.permissionValue = permissionValue == null ? null : permissionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.f_status
     *
     * @return the value of t_permission.f_status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.f_status
     *
     * @param status the value for t_permission.f_status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.f_created_time
     *
     * @return the value of t_permission.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.f_created_time
     *
     * @param createdTime the value for t_permission.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.f_modified_time
     *
     * @return the value of t_permission.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.f_modified_time
     *
     * @param modifiedTime the value for t_permission.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}