package com.springboot.demo.model;

import java.util.Date;

public class UserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_realname
     *
     * @mbg.generated
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_phone_no
     *
     * @mbg.generated
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_password_salt
     *
     * @mbg.generated
     */
    private String passwordSalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_source
     *
     * @mbg.generated
     */
    private Integer source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_last_login_ip
     *
     * @mbg.generated
     */
    private Integer lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_last_login_datetime
     *
     * @mbg.generated
     */
    private Date lastLoginDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_login_token
     *
     * @mbg.generated
     */
    private String loginToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_token_expire_time
     *
     * @mbg.generated
     */
    private Date tokenExpireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_role_summary
     *
     * @mbg.generated
     */
    private String roleSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_id
     *
     * @return the value of t_user.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_id
     *
     * @param id the value for t_user.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_version
     *
     * @return the value of t_user.f_version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_version
     *
     * @param version the value for t_user.f_version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_username
     *
     * @return the value of t_user.f_username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_username
     *
     * @param username the value for t_user.f_username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_realname
     *
     * @return the value of t_user.f_realname
     *
     * @mbg.generated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_realname
     *
     * @param realname the value for t_user.f_realname
     *
     * @mbg.generated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_email
     *
     * @return the value of t_user.f_email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_email
     *
     * @param email the value for t_user.f_email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_phone_no
     *
     * @return the value of t_user.f_phone_no
     *
     * @mbg.generated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_phone_no
     *
     * @param phoneNo the value for t_user.f_phone_no
     *
     * @mbg.generated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_password
     *
     * @return the value of t_user.f_password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_password
     *
     * @param password the value for t_user.f_password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_password_salt
     *
     * @return the value of t_user.f_password_salt
     *
     * @mbg.generated
     */
    public String getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_password_salt
     *
     * @param passwordSalt the value for t_user.f_password_salt
     *
     * @mbg.generated
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt == null ? null : passwordSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_level
     *
     * @return the value of t_user.f_level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_level
     *
     * @param level the value for t_user.f_level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_source
     *
     * @return the value of t_user.f_source
     *
     * @mbg.generated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_source
     *
     * @param source the value for t_user.f_source
     *
     * @mbg.generated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_last_login_ip
     *
     * @return the value of t_user.f_last_login_ip
     *
     * @mbg.generated
     */
    public Integer getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_last_login_ip
     *
     * @param lastLoginIp the value for t_user.f_last_login_ip
     *
     * @mbg.generated
     */
    public void setLastLoginIp(Integer lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_last_login_datetime
     *
     * @return the value of t_user.f_last_login_datetime
     *
     * @mbg.generated
     */
    public Date getLastLoginDatetime() {
        return lastLoginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_last_login_datetime
     *
     * @param lastLoginDatetime the value for t_user.f_last_login_datetime
     *
     * @mbg.generated
     */
    public void setLastLoginDatetime(Date lastLoginDatetime) {
        this.lastLoginDatetime = lastLoginDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_login_token
     *
     * @return the value of t_user.f_login_token
     *
     * @mbg.generated
     */
    public String getLoginToken() {
        return loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_login_token
     *
     * @param loginToken the value for t_user.f_login_token
     *
     * @mbg.generated
     */
    public void setLoginToken(String loginToken) {
        this.loginToken = loginToken == null ? null : loginToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_token_expire_time
     *
     * @return the value of t_user.f_token_expire_time
     *
     * @mbg.generated
     */
    public Date getTokenExpireTime() {
        return tokenExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_token_expire_time
     *
     * @param tokenExpireTime the value for t_user.f_token_expire_time
     *
     * @mbg.generated
     */
    public void setTokenExpireTime(Date tokenExpireTime) {
        this.tokenExpireTime = tokenExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_status
     *
     * @return the value of t_user.f_status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_status
     *
     * @param status the value for t_user.f_status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_role_summary
     *
     * @return the value of t_user.f_role_summary
     *
     * @mbg.generated
     */
    public String getRoleSummary() {
        return roleSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_role_summary
     *
     * @param roleSummary the value for t_user.f_role_summary
     *
     * @mbg.generated
     */
    public void setRoleSummary(String roleSummary) {
        this.roleSummary = roleSummary == null ? null : roleSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_created_time
     *
     * @return the value of t_user.f_created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_created_time
     *
     * @param createdTime the value for t_user.f_created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_modified_time
     *
     * @return the value of t_user.f_modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_modified_time
     *
     * @param modifiedTime the value for t_user.f_modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}